server:
  port: 8081
  error:
    include-message: always
spring:
  application:
    name: keycloak
  datasource:
    driver-class: mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/keycloak_example?createDatabaseIfNotExist=true
    username: ${BD_USER}
    password: ${BD_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/marlon-example
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
keycloak:
  url: http://localhost:8080/
  realm: marlon-example
  admin-user: ${KEYCLOAK_ADMIN}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}
  admin-client-id: admin-cli
  realm-admin: master

